# Generated by Django 5.2.12 on 2026-04-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_on_duty',
            field=models.BooleanField(default=False, help_text='Designates whether this staff member is currently working.'),
        ),
    ]
