# Generated by Django 5.2.12 on 2026-03-29 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepassrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gatepassrequest',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Permanent passes are active until resident cancels'),
        ),
        migrations.AddField(
            model_name='gatepassrequest',
            name='pass_type',
            field=models.CharField(choices=[('TEMPORARY', 'Temporary (Today Only)'), ('PERMANENT', 'Permanent (Until Cancelled)')], default='TEMPORARY', max_length=20),
        ),
        migrations.AddField(
            model_name='gatepassrequest',
            name='phone',
            field=models.CharField(blank=True, help_text="Visitor's contact number", max_length=20),
        ),
        migrations.AddField(
            model_name='gatepassrequest',
            name='purpose',
            field=models.CharField(blank=True, help_text='e.g. Family, Maid, Delivery', max_length=200),
        ),
        migrations.AlterField(
            model_name='gatepassrequest',
            name='expected_date',
            field=models.DateField(blank=True, help_text='Required for temporary passes', null=True),
        ),
    ]
